// To parse this JSON data, do
//
//     final ListOfTrips = getLatestTripDataFromJson(jsonString);

// import 'dart:convert';

// ListOfTrips listOfTripsFromJson(String str) =>
//     ListOfTrips.fromJson(json.decode(str));

// String listOfTripsToJson(ListOfTrips data) => json.encode(data.toJson());

// class ListOfTrips {
//   ListOfTrips({
//     required this.trip,
//     required this.driver,
//   });

//   List<Trip> trip;
//   Driver driver;

//   factory ListOfTrips.fromJson(Map<String, dynamic> json) => ListOfTrips(
//         trip: List<Trip>.from(json["trip"].map((x) => Trip.fromJson(x))),
//         driver: Driver.fromJson(json["driver"]),
//       );

//   Map<String, dynamic> toJson() => {
//         "trip": List<dynamic>.from(trip.map((x) => x.toJson())),
//         "driver": driver.toJson(),
//       };
// }

// class Driver {
//   Driver({
//     required this.id,
//     required this.name,
//     required this.dateofJoin,
//     required this.dob,
//     required this.age,
//     required this.licenseNo,
//     required this.licenseExpiry,
//     required this.totalTrips,
//     required this.totalTripsfortheMonth,
//     required this.assetNo,
//     required this.accountName,
//     required this.nextTripDate,
//     required this.mobileNo,
//   });
//
//   String id;
//   String name;
//   String dateofJoin;
//   String dob;
//   int age;
//   String licenseNo;
//   String licenseExpiry;
//   int totalTrips;
//   int totalTripsfortheMonth;
//   String assetNo;
//   String accountName;
//   String nextTripDate;
//   String mobileNo;
//
//   factory Driver.fromJson(Map<String, dynamic> json) => Driver(
//         id: json["id"] ?? "",
//         name: json["name"] ?? "",
//         dateofJoin: json["dateofJoin"] ?? "",
//         dob: json["dob"] ?? "",
//         age: json["age"] ?? 0,
//         licenseNo: json["licenseNo"] ?? "",
//         licenseExpiry: json["licenseExpiry"] ?? "",
//         totalTrips: json["totalTrips"] ?? 0,
//         totalTripsfortheMonth: json["totalTripsfortheMonth"] ?? "",
//         assetNo: json["assetNo"] ?? "",
//         accountName: json["accountName"] ?? "",
//         nextTripDate: json["nextTripDate"] ?? "",
//         mobileNo: json["mobileNo"] ?? "",
//       );
//
//   Map<String, dynamic> toJson() => {
//         "id": id,
//         "name": name,
//         "dateofJoin": dateofJoin,
//         "dob": dob,
//         "age": age,
//         "licenseNo": licenseNo,
//         "licenseExpiry": licenseExpiry,
//         "totalTrips": totalTrips,
//         "totalTripsfortheMonth": totalTripsfortheMonth,
//         "assetNo": assetNo,
//         "accountName": accountName,
//         "nextTripDate": nextTripDate,
//         "mobileNo": mobileNo,
//       };
// }
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListOfTripsDriver {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "Drivers Drivers(Driver)",
  "dateofJoin": "1900-01-01T00:00:00",
  "dob": "0001-01-01T00:00:00",
  "age": 123,
  "licenseNo": null,
  "licenseExpiry": "2023-03-31T00:00:00",
  "totalTrips": 0,
  "totalTripsfortheMonth": 0,
  "assetNo": "KA03AK2099          ",
  "accountName": "INTERNAL                                     ",
  "nextTripDate": "2023-04-14T16:30:00",
  "mobileNo": null
} 
*/

  String? id;
  String? name;
  String? dateofJoin;
  String? dob;
  int? age;
  String? licenseNo;
  String? licenseExpiry;
  int? totalTrips;
  int? totalTripsfortheMonth;
  String? assetNo;
  String? accountName;
  String? nextTripDate;
  String? mobileNo;

  ListOfTripsDriver({
    this.id,
    this.name,
    this.dateofJoin,
    this.dob,
    this.age,
    this.licenseNo,
    this.licenseExpiry,
    this.totalTrips,
    this.totalTripsfortheMonth,
    this.assetNo,
    this.accountName,
    this.nextTripDate,
    this.mobileNo,
  });
  ListOfTripsDriver.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    dateofJoin = json['dateofJoin']?.toString();
    dob = json['dob']?.toString();
    age = json['age']?.toInt();
    licenseNo = json['licenseNo']?.toString();
    licenseExpiry = json['licenseExpiry']?.toString();
    totalTrips = json['totalTrips']?.toInt();
    totalTripsfortheMonth = json['totalTripsfortheMonth']?.toInt();
    assetNo = json['assetNo']?.toString();
    accountName = json['accountName']?.toString();
    nextTripDate = json['nextTripDate']?.toString();
    mobileNo = json['mobileNo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['dateofJoin'] = dateofJoin;
    data['dob'] = dob;
    data['age'] = age;
    data['licenseNo'] = licenseNo;
    data['licenseExpiry'] = licenseExpiry;
    data['totalTrips'] = totalTrips;
    data['totalTripsfortheMonth'] = totalTripsfortheMonth;
    data['assetNo'] = assetNo;
    data['accountName'] = accountName;
    data['nextTripDate'] = nextTripDate;
    data['mobileNo'] = mobileNo;
    return data;
  }
}

class ListOfTrips {
/*
{
  "trip": null,
  "driver": {
    "id": "00000000-0000-0000-0000-000000000000",
    "name": "Drivers Drivers(Driver)",
    "dateofJoin": "1900-01-01T00:00:00",
    "dob": "0001-01-01T00:00:00",
    "age": 123,
    "licenseNo": null,
    "licenseExpiry": "2023-03-31T00:00:00",
    "totalTrips": 0,
    "totalTripsfortheMonth": 0,
    "assetNo": "KA03AK2099          ",
    "accountName": "INTERNAL                                     ",
    "nextTripDate": "2023-04-14T16:30:00",
    "mobileNo": null
  }
} 
*/

  List<Trip>? trip;
  ListOfTripsDriver? driver;

  ListOfTrips({
    this.trip,
    this.driver,
  });
  ListOfTrips.fromJson(Map<String, dynamic> json) {
    if (json['trip'] != null) {
      final v = json['trip'];
      final arr0 = <Trip>[];
      v.forEach((v) {
        arr0.add(Trip.fromJson(v));
      });
      trip = arr0;
    }
    driver = (json['driver'] != null)
        ? ListOfTripsDriver.fromJson(json['driver'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    if (driver != null) {
      data['driver'] = driver!.toJson();
    }
    return data;
  }
}

class Trip {
  Trip({
    required this.code,
    // required this.id,
    // required this.assetNo,
    // required this.invoiceNo,
    // required this.invoiceSlno,
    // required this.assetSerial,
    // required this.description,
    // required this.referenceNo,
    // required this.manufacturer,
    // required this.yearofMake,
    // required this.capacity,
    // required this.accountName,
    // required this.accunntBranch,
    // required this.driverName,
    // required this.driver,
    // required this.depot,
    // required this.lastTripCompletedDate,
    // required this.lastOdometerRecorded,
    // required this.nextServiceDue,
    // required this.warranties,
    // required this.documents,
    required this.noOfTrips,
    // required this.fuelEconomy,
    // required this.assetType,
    // required this.vehicleType,
    // required this.vehicleTypeDesp,
    // required this.category,
    // required this.categoryDesp,
    // required this.engineNo,
    // required this.chassisNo,
    // required this.modelasperRc,
    // required this.acNonAc,
    // required this.bodyCapacity,
    // required this.wheelBase,
    // required this.dateofReg,
    // required this.humanResources,
    // required this.make,
    // required this.madeBy,
    // required this.insuranceDue,
    // required this.permitRenewal,
    // required this.emissioncheckDate,
    // required this.createdByEntityId,
    // required this.createdBy,
    // required this.createdDate,
    // required this.modifiedBy,
    // required this.modifiedDate,
    // required this.createdByEntity,
    // required this.dbOperation,
  });

  String code;
  // String id;
  // String assetNo;
  // String invoiceNo;
  // String invoiceSlno;
  // String assetSerial;
  // String description;
  // String referenceNo;
  // String manufacturer;
  // String yearofMake;
  // String capacity;
  // String accountName;
  // String accunntBranch;
  // String driverName;
  // String driver;
  // String depot;
  // String lastTripCompletedDate;
  // int lastOdometerRecorded;
  // String nextServiceDue;
  // String warranties;
  // String documents;
  int noOfTrips;
  // int fuelEconomy;
  // String assetType;
  // String vehicleType;
  // String vehicleTypeDesp;
  // String category;
  // String categoryDesp;
  // String engineNo;
  // String chassisNo;
  // String modelasperRc;
  // String acNonAc;
  // String bodyCapacity;
  // String wheelBase;
  // String dateofReg;
  // String humanResources;
  // String make;
  // String madeBy;
  // String insuranceDue;
  // String permitRenewal;
  // String emissioncheckDate;
  // int createdByEntityId;
  // String createdBy;
  // String createdDate;
  // String modifiedBy;
  // String modifiedDate;
  // String createdByEntity;
  // String dbOperation;

  factory Trip.fromJson(Map<String, dynamic> json) => Trip(
        code: json["code"] ?? "",
        // id: json["id"] ?? "",
        // assetNo: json["assetNo"] ?? "",
        // invoiceNo: json["invoiceNo"] ?? "",
        // invoiceSlno: json["invoiceSlno"] ?? "",
        // assetSerial: json["assetSerial"] ?? "",
        // description: json["description"] ?? "",
        // referenceNo: json["referenceNo"] ?? "",
        // manufacturer: json["manufacturer"] ?? "",
        // yearofMake: json["yearofMake"] ?? "",
        // capacity: json["capacity"] ?? "",
        // accountName: json["accountName"] ?? "",
        // accunntBranch: json["accunntBranch"] ?? "",
        // driverName: json["driverName"] ?? "",
        // driver: json["driver"] ?? "",
        // depot: json["depot"] ?? "",
        // lastTripCompletedDate: json["lastTripCompletedDate"] ?? "",
        // lastOdometerRecorded: json["lastOdometerRecorded"] ?? "",
        // nextServiceDue: json["nextServiceDue"] ?? "",
        // warranties: json["warranties"] ?? "",
        // documents: json["documents"] ?? "",
        noOfTrips: json["noOfTrips"] ?? 0,
        // fuelEconomy: json["fuelEconomy"] ?? 0,
        // assetType: json["assetType"] ?? "",
        // vehicleType: json["vehicleType"] ?? "",
        // vehicleTypeDesp: json["vehicleTypeDesp"] ?? "",
        // category: json["category"] ?? "",
        // categoryDesp: json["categoryDesp"] ?? "",
        // engineNo: json["engineNo"] ?? "",
        // chassisNo: json["chassisNo"] ?? "",
        // modelasperRc: json["modelasperRC"] ?? "",
        // acNonAc: json["acNonAC"] ?? "",
        // bodyCapacity: json["bodyCapacity"] ?? "",
        // wheelBase: json["wheelBase"] ?? "",
        // dateofReg: json["dateofReg"] ?? "",
        // humanResources: json["humanResources"] ?? "",
        // make: json["make"] ?? "",
        // madeBy: json["madeBy"] ?? "",
        // insuranceDue: json["insuranceDue"] ?? "",
        // permitRenewal: json["permitRenewal"] ?? "",
        // emissioncheckDate: json["emissioncheckDate"] ?? "",
        // createdByEntityId: json["createdByEntityId"] ?? 0,
        // createdBy: json["createdBy"] ?? "",
        // createdDate: json["createdDate"] ?? "",
        // modifiedBy: json["modifiedBy"] ?? "",
        // modifiedDate: json["modifiedDate"] ?? "",
        // createdByEntity: json["createdByEntity"] ?? "",
        // dbOperation: json["dbOperation"] ?? "",
      );

  Map<String, dynamic> toJson() => {
        "code": code,
        // "id": id,
        // "assetNo": assetNo,
        // "invoiceNo": invoiceNo,
        // "invoiceSlno": invoiceSlno,
        // "assetSerial": assetSerial,
        // "description": description,
        // "referenceNo": referenceNo,
        // "manufacturer": manufacturer,
        // "yearofMake": yearofMake,
        // "capacity": capacity,
        // "accountName": accountName,
        // "accunntBranch": accunntBranch,
        // "driverName": driverName,
        // "driver": driver,
        // "depot": depot,
        // "lastTripCompletedDate": lastTripCompletedDate,
        // "lastOdometerRecorded": lastOdometerRecorded,
        // "nextServiceDue": nextServiceDue,
        // "warranties": warranties,
        // "documents": documents,
        "noOfTrips": noOfTrips,
        // "fuelEconomy": fuelEconomy,
        // "assetType": assetType,
        // "vehicleType": vehicleType,
        // "vehicleTypeDesp": vehicleTypeDesp,
        // "category": category,
        // "categoryDesp": categoryDesp,
        // "engineNo": engineNo,
        // "chassisNo": chassisNo,
        // "modelasperRC": modelasperRc,
        // "acNonAC": acNonAc,
        // "bodyCapacity": bodyCapacity,
        // "wheelBase": wheelBase,
        // "dateofReg": dateofReg,
        // "humanResources": humanResources,
        // "make": make,
        // "madeBy": madeBy,
        // "insuranceDue": insuranceDue,
        // "permitRenewal": permitRenewal,
        // "emissioncheckDate": emissioncheckDate,
        // "createdByEntityId": createdByEntityId,
        // "createdBy": createdBy,
        // "createdDate": createdDate,
        // "modifiedBy": modifiedBy,
        // "modifiedDate": modifiedDate,
        // "createdByEntity": createdByEntity,
        // "dbOperation": dbOperation,
      };
}
